"""add composite indexes, recurring transactions, notifications, audit logs

Revision ID: 1dbed29f2b0a
Revises: f7c3dd8221ad
Create Date: 2026-04-15 00:29:48.166728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1dbed29f2b0a'
down_revision: Union[str, None] = 'f7c3dd8221ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###