"""add composite indexes, recurring transactions, notifications, audit logs

Revision ID: 49c3bc4ba719
Revises: 1dbed29f2b0a
Create Date: 2026-04-15 02:07:19.303323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49c3bc4ba719'
down_revision: Union[str, None] = '1dbed29f2b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###