"""add composite indexes, recurring transactions, notifications, audit logs

Revision ID: 5e5101acebd7
Revises: cc30676043db
Create Date: 2026-04-15 10:30:59.378675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5e5101acebd7'
down_revision: Union[str, None] = 'cc30676043db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###