"""add composite indexes, recurring transactions, notifications, audit logs

Revision ID: cc30676043db
Revises: 49c3bc4ba719
Create Date: 2026-04-15 02:08:49.522974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cc30676043db'
down_revision: Union[str, None] = '49c3bc4ba719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###